services:
  db:
    build: ./docker
    container_name: bonsai_postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env

volumes:
  pgdata:
